name: Conor Test
favicon: null
layout_spectrum: 0.9526382167823613
typography_spectrum: 0.7440722743049264
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5531458298210055
  lightness: 0.5721159663517028
  saturation: 0.3757555214688182
  rhythmicContrast: 0.1968965616542846
purpose: []
